project:
  type: website
  output-dir: docs

website:
  title: "Tom's blog"
  site-url: https://thomashallam.github.io/
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-EMB22EEKPF"
    anonymize-ip: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/thomashallam
      - icon: twitter
        href: https://twitter.com/thomashallam
      - icon: linkedin
        href: https://linkedin.com/in/thomashallam        
format:
  html:
    theme: cosmo
    css: styles.css



