project:
  type: website
  output-dir: docs

website:
  title: "Tom's blog"
  site-url: https://thomashallam.github.io/
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-EMB22EEKPF"
    storage: cookies
    anonymize-ip: false
  navbar:
    right:
      - about.qmd
      - data-sci/datasci.qmd
      - icon: github
        href: https://github.com/thomashallam
      - icon: twitter
        href: https://twitter.com/thomashallam
      - icon: linkedin
        href: https://linkedin.com/in/thomashallam        
format:
  html:
    theme: cosmos
    css: styles.css



